kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mywebapp
  labels:
    app: mywebapp
spec:
  host: 
  path: /
  to:
    kind: Service
    name: mywebapp
    weight: 100
  port:
    targetPort: flask
  tls:
    termination: edge
  wildcardPolicy: None
