kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  host: 
  path: /
  to:
    kind: Service
    name: myhelmapp
    weight: 100
  port:
    targetPort: flask
  tls:
    termination: edge
  wildcardPolicy: None
